name: Release

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.22
            - name: Build
              run: sh scripts/build.sh
            - uses: ncipollo/release-action@v1
              with:
                artifacts: "dist/bin/*,configs/*"
                token: ${{ secrets.GITHUB_TOKEN }}